/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.beaconartifact.model;


import android.graphics.drawable.Drawable;

public class Artifact {

    private String artifactID;
    private String artifactName;
    private String artifactDescription;
    private Drawable artifactImage;


    public Artifact(String artifactID, String artifactName, String artifactDescription, Drawable artifactImage) {
        this.artifactID = artifactID;
        this.artifactName = artifactName;
        this.artifactDescription = artifactDescription;
        this.artifactImage = artifactImage;
    }


    public String getArtifactID() {
        return artifactID;
    }

    public String getArtifactName() {
        return artifactName;
    }

    public String getArtifactDescription() {
        return artifactDescription;
    }

    public Drawable getArtifactImage() {
        return artifactImage;
    }

}
